name: CI/CD SAM Pipeline


on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest


    env:
      AWS_REGION: us-east-1
      STACK_NAME: danielDevOps

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4


    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}


    - name: Set up SAM CLI
      uses: aws-actions/setup-sam@v2
      with:
        version: 1.129.0


    - name: SAM Build
      run: sam build


    - name: SAM Deploy
      run: |
        sam deploy \
          --stack-name ${STACK_NAME} \
          --region ${AWS_REGION} \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
